### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by askfriends** [rahulps1000/HerokuBannedDeployer#2]
How does this work? what after being successfully deployed to heroku or railway?

**Comment by rahulps1000** [comment]
Manually set up all environmental variables and your app will be working as usual

**Comment by askfriends** [comment]
> Manually set up all environmental variables and your app will be working as usual

No i mean where to set all variables?
lets say i have a repo which is banned from heroku, so how to deploy that?
sorry for being noob here.

**Comment by rahulps1000** [comment]
You set var in the app setting in heroku and railway

**Comment by askfriends** [comment]
> You set var in the app setting in heroku and railway

ok i will try that and will see if it works. thanks

**Comment by askfriends** [comment]
bro can we deploy mirror bot throught this?
